# Generated by Django 4.0.3 on 2022-03-12 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('left_offset', models.IntegerField(blank=True, default=0, null=True)),
                ('right_offset', models.IntegerField(blank=True, default=0, null=True)),
                ('width', models.IntegerField(blank=True, default=0, null=True)),
                ('length', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('emteredAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('direction', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('capture', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('captureSpeed', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('capturedAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
