# Generated by Django 4.0.3 on 2022-03-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('v1', models.IntegerField(blank=True, default=0, null=True)),
                ('v2', models.IntegerField(blank=True, default=0, null=True)),
                ('v3', models.IntegerField(blank=True, default=0, null=True)),
                ('v4', models.IntegerField(blank=True, default=0, null=True)),
                ('v5', models.IntegerField(blank=True, default=0, null=True)),
                ('v6', models.IntegerField(blank=True, default=0, null=True)),
                ('v7', models.IntegerField(blank=True, default=0, null=True)),
                ('v8', models.IntegerField(blank=True, default=0, null=True)),
                ('v9', models.IntegerField(blank=True, default=0, null=True)),
                ('concludedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
