# Generated by Django 4.0.3 on 2022-03-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='direction',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='manual',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='manual',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True),
        ),
    ]
